## Практическое задание 4_1.

__1.__ Решите систему уравнений методом Гаусса:

$$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$$

__2.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений:

   а) $\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0;
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-4x_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5;
\end{cases}$
    
   в) $\begin{cases}
x_{1}+2x_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2. 
\end{cases}$


__3.__ Проверьте на совместность и выясните, сколько решений будет иметь система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 3 & -2 & 4\\ 
0 & 5 & 0 & 1\\ 
0 & 0 & 3 & 0\\ 
0 & 0 & 0 & 2
\end{matrix}\right|
\begin{matrix}
3\\ 
2\\
4\\
1
\end{matrix}
\end{pmatrix}.$$

__4.__ Дана система линейных уравнений, заданная расширенной матрицей:

$$\tilde{A}=\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$$

Найдите соотношение между параметрами $a$, $b$ и $c$, при которых система считается несовместной.

## 1.

Число уравнений меньше числа неизвестных, поэтому система уравнений недоопределённая.


$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
2x_{1}+x_{2}-x_{3}+x_{4}=-2, \\
x_{1}+x_{2}-3x_{3}+x_{4}=4.
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
1 & 1 & -3 & 1
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$

Вычтем из третьей строки первую:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
2 & 1 & -1 & 1\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$

Вычтем из второй строки первую, умноженную на 2:

$\begin{pmatrix}
\left.\begin{matrix}
1 & 1 & -1 & -2\\ 
0 & -1 & 1 & 5\\ 
0 & 0 & -2 & 3
\end{matrix}\right|
\begin{matrix}
0\\ 
-2\\
4
\end{matrix}
\end{pmatrix}.$

Матрица соответствует системе:

$\begin{cases}
x_{1}+x_{2}-x_{3}-2x_{4}=0, \\
~~ -x_{2}+x_{3}+5x_{4}=-2, \\
~~  -2x_{3}+3x_{4}=4.
\end{cases}$

В полученном ступенчатом виде мы имеем ступеньки из трех чисел, а не из четырех, как это требуется. В таком случае система имеет бесконечное количество решений.


## 2.

a)
$\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
2x_{1}-5x_{2}-3x_{3}=-17, \\
x_{1}+x_{2}-x_{3}=0.
\end{cases}$


$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
0 & 1 & -1
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
0
\end{matrix}
\end{pmatrix}.$


$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
2 & -5 & -3 \\ 
0 & 4 & -4
\end{matrix}\right|
\begin{matrix}
4\\ 
-17\\
-4
\end{matrix}
\end{pmatrix}.$


$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
0 & -13 & -11 \\ 
0 & 4 & -4
\end{matrix}\right|
\begin{matrix}
4\\ 
-59\\
-4
\end{matrix}
\end{pmatrix}.$


$\begin{pmatrix}
\left.\begin{matrix}
3 & -1 & 1 \\ 
0 & -13 & -11 \\ 
0 & 0 & -96
\end{matrix}\right|
\begin{matrix}
4\\ 
-59\\
-288
\end{matrix}
\end{pmatrix}.$



$$\begin{cases}
3x_{1}-x_{2}+x_{3}=4, \\
~-13x_{2}-11x_{3}=-59, \\
~~~~~~~~~~~~~~~~~-96x_{3}=-288.
\end{cases}$$


$$x_{3}=3$$
$$x_{2}=2$$
$$x_{1}=1$$

б)
$\begin{cases}
2x_{1}-4_{2}+6x_{3}=1, \\
x_{1}-2x_{2}+3x_{3}=-2, \\
3x_{1}-6x_{2}+9x_{3}=5.
\end{cases}$

$\begin{pmatrix}
\left.\begin{matrix}
2 & -4 & 6 \\ 
1 & -2 & 3 \\ 
3 & -6 & 9
\end{matrix}\right|
\begin{matrix}
1\\ 
-2\\
5
\end{matrix}
\end{pmatrix}.$

Векторы коэффициентов первого столбца равны векторам коэффициентов третьего столбца, умноженных на 3. Таким образом, этими векторами образовано некое линейное подпространство, которому результирующий вектор не принадлежит. Система несовместна.

в)
$\begin{cases}
x_{1}+2_{2}+5x_{3}=4, \\
3x_{1}+x_{2}-8x_{3}=-2.
\end{cases}$

Число уравнений меньше числа неизвестных, поэтому система уравнений недоопределённая, имеет бесконечное количество решений, зависящих от переменной х3.

## 3.

попробовать функции Numpy

In [1]:
import numpy as np
from numpy import linalg as LA

In [22]:
a = np.array([[1, 3, -2, 4],[0, 5, 0, 1],[0, 0, 3, 0],[0, 0, 0, 2]])
b = np.array([3, 2, 4, 1])
x = LA.solve(a, b)
x

array([2.76666667, 0.3       , 1.33333333, 0.5       ])

In [23]:
np.dot(a, x)

array([3., 2., 4., 1.])

## 4.


$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
7 & 8 & 9
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c
\end{matrix}
\end{pmatrix}.$


$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
4 & 5 & 6 \\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b\\
c-7a
\end{matrix}
\end{pmatrix}.$


$\begin{pmatrix}
\left.\begin{matrix}
1 & 2 & 3 \\ 
0 & -3 & -6 \\ 
0 & -6 & -12
\end{matrix}\right|
\begin{matrix}
a\\ 
b-4a\\
c-7a
\end{matrix}
\end{pmatrix}.$


$2(b - 4a) = c - 7a,\\
7a - 8a + 2b - c = 0,\\
-a + 2b - c = 0,\\
a - 2b + c = 0.$

## Практическое задание 4_2.

__1.__ Решите систему уравнений методом Крамера:

   а) $\begin{cases}
x_{1}-2x_{2}=1 \\
3x_{1}-4x_{2}=7
\end{cases}$
    
   б) $\begin{cases}
2x_{1}-x_{2}+5x_{3}=10 \\
x_{1}+x_{2}-3x_{3}=-2 \\
2x_{1}+4x_{2}+x_{3}=1
\end{cases}$

__2*.__ Найдите $L$-матрицу $LU$-разложения для матрицы коэффициентов:

   а)$$\begin{pmatrix}
1 & 2 & 4 \\ 
2 & 9 & 12 \\ 
3 & 26 & 30
\end{pmatrix}$$
    
   б)$$\begin{pmatrix}
1 & 1 & 2 & 4\\ 
2 & 5 & 8 & 9\\ 
3 & 18 & 29 & 18\\
4 & 22 & 53 & 33
\end{pmatrix}$$
    
__3*.__ Решите систему линейных уравнений методом $LU$-разложения:

$$\begin{cases}
2x_{1}+x_{2}+3x_{3}=1 \\
11x_{1}+7x_{2}+5x_{3}=-6 \\
9x_{1}+8x_{2}+4x_{3}=-5
\end{cases}$$

__4*.__ Решите систему линейных уравнений методом Холецкого:

$$\begin{cases}
81x_{1}-45x_{2}+45x_{3}=531 \\
-45x_{1}+50x_{2}-15x_{3}=-460 \\
45x_{1}-15x_{2}+38x_{3}=193
\end{cases}$$

__5*.__ Напишите на Python программу с реализацией одного из изученных алгоритмов решения СЛАУ.

## 1.

a)
$\begin{cases}
x_{1}-2x_{2}=1, \\
3x_{1}-4x_{2}=7.
\end{cases}$


$detA=\begin{vmatrix}
1 & -2\\ 
3 & -4
\end{vmatrix}=
-4+6=2\neq 0,$

система совместна.

Oпределители $detA_{1}$, $detA_{2}$:

$detA_{1}=\begin{vmatrix}
1 & -2\\
7 & -4
\end{vmatrix}=
-4+14=10,$

$detA_{2}=\begin{vmatrix}
1 & 1\\
3 & 7
\end{vmatrix}=
7-3=4,$

$$x_{1} = \frac{detA_{1}}{detA} = \frac{10}{2}=5,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{4}{2}=2,$$


б)
$\begin{cases}
2x_{1}-x_{2}+5x_{3}=10, \\
x_{1}+x_{2}-3x_{3}=-2, \\
2x_{1}+4x_{2}+x_{3}=1.
\end{cases}$


$detA=\begin{vmatrix}
2 & -1 & 5\\ 
1 & 1 & -3\\ 
2 & 4 & 1
\end{vmatrix}=
2+6+20-(10-24-1)=28+15=43\neq 0,$

система совместна.

Oпределители $detA_{1}$, $detA_{2}$, $detA_{3}$:

$detA_{1}=\begin{vmatrix}
10 & -1 & 5\\ 
-2 & 1 & -3\\ 
1 & 4 & 1
\end{vmatrix}=
10+3-40-(5-120+2)=-27+113=86,$

$detA_{2}=\begin{vmatrix}
2 & 10 & 5\\ 
1 & -2 & -3\\ 
2 & 1 & 1
\end{vmatrix}=
-4-60+5-(-20-6+10)=-59+16=-43,$

$detA_{3}=\begin{vmatrix}
2 & -1 & 10\\ 
1 & 1 & -2\\ 
2 & 4 & 1
\end{vmatrix}=
2+4+40-(20-16-1)=43,$


$$x_{1} = \frac{detA_{1}}{detA} = \frac{86}{43}=2,$$

$$x_{2} = \frac{detA_{2}}{detA} = \frac{-43}{43}=-1,$$

$$x_{3} = \frac{detA_{3}}{detA} = \frac{43}{43}=1.$$


## 2.

In [5]:
pip install scipy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\okayu\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [10]:
from scipy.linalg import lu_factor, lu_solve

In [17]:
A = np.array([[1, 2, 4], [2, 9, 12], [3, 26, 30]])

lu, piv = lu_factor(A)
piv
lu

array([[ 3.        , 26.        , 30.        ],
       [ 0.66666667, -8.33333333, -8.        ],
       [ 0.33333333,  0.8       ,  0.4       ]])

In [18]:
A = np.array([[1, 1, 2, 4], [2, 5, 8, 9], [3, 18, 29, 18], [4, 22, 53, 33]])

lu, piv = lu_factor(A)
piv
lu

array([[  4.        ,  22.        ,  53.        ,  33.        ],
       [  0.5       ,  -6.        , -18.5       ,  -7.5       ],
       [  0.75      ,  -0.25      , -15.375     ,  -8.625     ],
       [  0.25      ,   0.75      ,  -0.17073171,  -0.09756098]])

## 3.

In [19]:
A = np.array([[2, 1, 3], [11, 7, 5], [9, 8, 4]])
b = np.array([1, -6, -5])

lu, piv = lu_factor(A)

x = lu_solve((lu, piv), b)
x

array([-1.,  0.,  1.])

In [15]:
np.dot(A, x)

array([ 1., -6., -5.])

## 4.

In [24]:
from scipy.linalg import cho_factor, cho_solve

In [30]:
A = np.array([[81, -45, 45], [-45, 50, -15], [45, -15, 38]])
b = np.array([531, -460, 193])

c, low = cho_factor(A)
x = cho_solve((c, low), b)
x

array([ 6., -5., -4.])

In [31]:
np.dot(A, x)

array([ 531., -460.,  193.])