## Практическое задание 5.

1. Найдите посредством NumPy SVD для матрицы:

$$\begin{pmatrix}
1 & 2 & 0\\ 
0 & 0 & 5\\ 
3 & -4 & 2\\ 
1 & 6 & 5\\ 
0 & 1 & 0
\end{pmatrix}.$$


2. Для матрицы из предыдущего задания найдите:

    а) евклидову норму;
    
    б) норму Фробениуса.

In [44]:
import numpy as np
np.set_printoptions(precision=0, suppress=True)

In [45]:
A = np.array([[1, 2, 0],[0, 0, 5],[3, -4, 2],[1, 6, 5],[0, 1, 0]])
print(f'Матрица A:\n{A}')

Матрица A:
[[ 1  2  0]
 [ 0  0  5]
 [ 3 -4  2]
 [ 1  6  5]
 [ 0  1  0]]


In [46]:
U, s, W = np.linalg.svd(A)
V = W.T

D = np.zeros_like(A, dtype=float)
D[np.diag_indices(min(A.shape))] = s

print(f'Матрица D:\n{D}')

Матрица D:
[[9. 0. 0.]
 [0. 6. 0.]
 [0. 0. 3.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [47]:
print(f'Матрица U:\n{U}')

Матрица U:
[[ 0.  0. -1. -1. -0.]
 [ 0. -1.  1. -0.  0.]
 [-0. -1. -1.  0.  0.]
 [ 1.  0. -0.  0. -0.]
 [ 0.  0. -0. -0.  1.]]


In [48]:
print(f'Матрица V:\n{V}')

Матрица V:
[[ 0. -0. -1.]
 [ 1.  1. -0.]
 [ 1. -1.  0.]]


In [49]:
print(np.dot(np.dot(U, D), V.T))

[[ 1.  2. -0.]
 [-0.  0.  5.]
 [ 3. -4.  2.]
 [ 1.  6.  5.]
 [ 0.  1.  0.]]


Евклидова норма матрицы равна евклидовой норме диагональной матрицы из её сингулярных чисел $D$.Максимальное значение полученного отношения будет равно максимальному сингулярному числу $\mu_{max}$.

$$\left \| A \right \|_{E}=\mu_{max}$$

In [58]:
from scipy.linalg import svdvals, norm

In [59]:
norm(D, 2)

8.824868854820448

In [60]:
a_d = svdvals(A)
d = a_d.reshape(3,1)
d

array([[9.],
       [6.],
       [3.]])

In [61]:
norm(d, np.inf)

8.824868854820442

Когда известно сингулярное разложение матрицы, её норма Фробениуса вычисляется как:

$$\left \| A \right \|_{F}=\sqrt{\sum_{k=1}^{r}\mu_{k}^{2}}=\sqrt{9^{2}+6^{2}+3^{2}}=11,225$$

In [62]:
norm(d, 'fro')

11.04536101718726