# Практическое задание 3.





__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.



**4.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

## 1.

In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\okayu\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [2]:
import numpy as np
np.set_printoptions(precision=0, suppress=True)

In [3]:
A = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(A)
 
print(f'Матрица A:\n{A}')
print(f'Собственные векторы:\n{v}')
print(f'Собственные значения:\n{w}')

Матрица A:
[[-1 -6]
 [ 2  6]]
Собственные векторы:
[[-1.  1.]
 [ 0. -1.]]
Собственные значения:
[2. 3.]


## 2.

In [4]:
A = np.array([[-1, 0], [0, -1]])
print(f'Матрица A:\n{A}')

Матрица A:
[[-1  0]
 [ 0 -1]]


$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x\\ 
y
\end{pmatrix}=
\lambda
\begin{pmatrix}
x\\ 
y
\end{pmatrix}. \lambda=?
$

$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x\\ 
y
\end{pmatrix}=
\begin{pmatrix}
-x\\ 
-y
\end{pmatrix}=
(-1)
\begin{pmatrix}
x\\ 
y
\end{pmatrix}
$

Таким образом, для линейного оператора А любой вектор будет собственным и зеркальным (с поворотом 180 гр)

## 3.

In [5]:
A = np.array([[1, 1], [-1, 3]])
x = np.array([1, 1])
print(f'Матрица Ax\n{np.dot(A, x)}')

Матрица Ax
[2 2]


$\begin{cases}
\lambda=2\\ 
\lambda=2
\end{cases}$

Вектор $x=(1,1)$ считается собственным вектором линейного оператора, заданного матрицей $A$, $\lambda=2$

## 4.

In [6]:
A = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
x = np.array([3, -3, -4])
print(f'Матрица Ax\n{np.dot(A, x)}')

Матрица Ax
[ -9   9 -12]


$\begin{cases}
-9=3\cdot\lambda \\ 
9=-3\cdot\lambda \\ 
-12=-4\cdot\lambda
\end{cases}
\Rightarrow
\begin{cases}
\lambda=-3\\ 
\lambda=3\\ 
\lambda=3
\end{cases}$

Cистема не имеет смысла, следовательно, вектор $x=(3,-3,-4)$ не считается собственным вектором линейного оператора, заданного матрицей $A$