# Практическое задание 2.1

In [21]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\okayu\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [22]:
import numpy as np



__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.
    
__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$
    
__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

__5*.__ Напишите на Python функцию для перемножения двух произвольных матриц, не используя NumPy.

## 1.

a) A(4x2)*B(4x2) определено, размерность (4,2) \
   В(4x2)*A(4x2) не определено - число столбцов В не равно числу строк А

б) A(2x5)*B(5x3) определено, размерность (2,3) \
   В(5x3)*A(2x5) не определено - число столбцов В не равно числу строк А

в) A(8x3)*B(3x8) определено, размерность (8,8) \
   В(3x8)*A(8x3) определено, размерность (3,3)

г) A(4x4)*B(4x4) определено, размерность (4,4) \
   В(4x4)*A(4x4) определено, размерность (4,4)

# 2.

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ + $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}$

$A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ * $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}$

In [23]:
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'Матрица A + B\n{A + B}')
print(f'Матрица AB\n{np.dot(A, B)}')

Матрица A + B
[[ 5 -3]
 [ 3  5]]
Матрица AB
[[  4 -11]
 [ 12  -3]]


# 3.

3 * $\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$ - 2 * $\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$ + 4 * $\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}$ = $\begin{pmatrix}
3 & 21\\ 
9 & -18
\end{pmatrix}$ - $\begin{pmatrix}
0 & 10\\ 
4 & -2
\end{pmatrix}$ + $\begin{pmatrix}
8 & -16\\ 
4 & 4
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}$

In [24]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])

print(f'Матрица 3*А-2*B+4*C\n{3*A-2*B+4*C}')

Матрица 3*А-2*B+4*C
[[ 11  -5]
 [  9 -12]]


# 4.

$A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\
2 & 3
\end{pmatrix}$  $A.T=\begin{pmatrix}
4 & 5 & 2\\ 
1 & -2 & 3
\end{pmatrix}$

In [25]:
A = np.array([[4, 1], [5, -2], [2, 3]])

print(f'Матрица:\n{A}')
print(f'Транспонированная матрица:\n{A.T}')

Матрица:
[[ 4  1]
 [ 5 -2]
 [ 2  3]]
Транспонированная матрица:
[[ 4  5  2]
 [ 1 -2  3]]


In [26]:
print(f'Матрица A*A.T\n{np.dot(A, A.T)}')
print(f'Матрица A.T*A\n{np.dot(A.T, A)}')

Матрица A*A.T
[[17 18 11]
 [18 29  4]
 [11  4 13]]
Матрица A.T*A
[[45  0]
 [ 0 14]]


# 5.

In [27]:
def matrixmult (A, B):
    C = [[0 for row in range(len(B[0]))] for col in range(len(A))]
    for i in range(len(A)):
        for j in range(len(B[0])):
            for k in range(len(B)):
                C[i][j] += A[i][k]*B[k][j]
    return C

X = np.array([[1, -2], [3, 0]])
Y = np.array([[4, -1], [0, 5]])
print(f'Матрица AB\n{matrixmult(X, Y)}')

Матрица AB
[[4, -11], [12, -3]]


# Практическое задание 2.2



__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$


__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.
   
__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

# 1.

a)

$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix} = sin^{2}x + cos^{2}x = 1$

б)
    
$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix} = 180+0+0-0-0-0 = 180$

в)

$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix} = 45 + 84 +96 - 105 - 48 -72 = 225 -225 = 0$

In [28]:
a = np.array([[4, 2, 3], [0, 5, 1], [0, 0, 9]])

print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
180


In [29]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(f'Определитель:\n{np.linalg.det(a):.0f}')

Определитель:
0


# 2.

а) $det(A^{2}) = (detA)^{2} = 4^{2} = 16$

б) $det(A^{T}) = detA = 4$

в) $det(2A) = 2^{n} * detA = 2^{n+2}$ , где n - порядок матрицы

# 3.

$\begin{vmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} => \begin{vmatrix}
0 & 0 & 0\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{vmatrix} = 0$ если определитель 0, матрица вырожденная

# 4.

а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix} => \begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
0 & 0 & 0
\end{pmatrix}$ ранг 2

б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix} => $ ранг 4