# Практическое задание 1

### 1. Найдите скалярное произведение векторов 𝑥,𝑦∈ℝ:
а) 𝑥=(0,−3,6), 𝑦=(−4,7,9);
б) 𝑥=(7,−4,0,1), 𝑦=(−3,1,11,2).

In [69]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\okayu\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.


In [70]:
import numpy as np

In [71]:
xy=0+(-21)+54
xy

33

In [72]:
x = np.array([0, -3, 6])
y = np.array([-4, 7, 9])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
33


In [73]:
xy=-21+(-4)+0+2
xy

-23

In [74]:
x = np.array([7, -4, 0, 1])
y = np.array([-3, 1, 11, 2])
print(f'Скалярное произведение x и y:\n{np.dot(x, y)}')

Скалярное произведение x и y:
-23


### 2. Найдите нормы векторов (4,2,4) и (12,3,4) и угол между ними.

In [75]:
from numpy.linalg import norm

In [76]:
x = np.array([4, 2, 4])
y = np.array([12, 3, 4])

In [77]:
print(f'Норма вектора x:\n{norm(x, ord=2)}')
print(f'Норма вектора y:\n{norm(y, ord=2)}')

Норма вектора x:
6.0
Норма вектора y:
13.0


In [78]:
cos_xy = np.dot(x, y) / (norm(x) * norm(y))
print(f'Угол между векторами x и y:\n{np.arccos(cos_xy)}')

Угол между векторами x и y:
0.45687400353266105


### 3. Определите, будет ли линейное пространство евклидовым, если за скалярное произведение принять:
а) произведение длин векторов;
б) утроенное обычное скалярное произведение векторов?

### Если в линейном пространстве определено скалярное произведение, то такое пространство называется евклидовым пространством. 
### В том числе утроенное скалярное произведение: 3·(x, y). Ответ б)


### 4. Выясните, какие из нижеперечисленных векторов образуют ортонормированный базис в линейном пространстве ℝ3:
а) (1,0,0),(0,0,1);
б) (1/2⎯⎯√,−1/2⎯⎯√,0),(1/2⎯⎯√,1/2⎯⎯√,0),(0,0,1);
в) (1/2,−1/2,0),(0,1/2,1/2),(0,0,1);
г) (1,0,0),(0,1,0),(0,0,1)?

### условие ортонормированности (x,y)=0 и norm=1

### а) (1,0,0),(0,0,1)

In [79]:
a1 = np.array([1, 0, 0])
a2 = np.array([0, 0, 1])
print(f'Скалярное произведение a1 и a2:\n{np.dot(a1, a2)}')
print(f'Норма вектора a1:\n{norm(a1, ord=2)}')
print(f'Норма вектора a2:\n{norm(a2, ord=2)}')

Скалярное произведение a1 и a2:
0
Норма вектора a1:
1.0
Норма вектора a2:
1.0


### а) векторы ортонормированны

### б) (1/2⎯⎯√,−1/2⎯⎯√,0),(1/2⎯⎯√,1/2⎯⎯√,0),(0,0,1)

In [80]:
s = 1/np.sqrt(2)
s

0.7071067811865475

In [81]:
b1 = np.array([s, -s, 0])
b2 = np.array([s, s, 0])
b3 = np.array([0, 0, 1])

print(f'Скалярное произведение b1 b2 b3:\n{np.dot(np.dot(b1, b2), b3)}')
print(f'Норма вектора b1:\n{norm(b1, ord=2)}')
print(f'Норма вектора b2:\n{norm(b2, ord=2)}')
print(f'Норма вектора b3:\n{norm(b3, ord=2)}')

Скалярное произведение b1 b2 b3:
[0. 0. 0.]
Норма вектора b1:
0.9999999999999999
Норма вектора b2:
0.9999999999999999
Норма вектора b3:
1.0


### б) векторы ортонормированны

### в) (1/2,−1/2,0),(0,1/2,1/2),(0,0,1)

In [82]:
v1 = np.array([1/2, -1/2, 0])
v2 = np.array([0, 1/2, 1/2])
v3 = np.array([0, 0, 1])
print(f'Скалярное произведение в1, в2, в3:\n{np.dot(np.dot(v1, v2), v3)}')
print(f'Норма вектора в1:\n{norm(v1, ord=2)}')
print(f'Норма вектора в2:\n{norm(v2, ord=2)}')
print(f'Норма вектора в3:\n{norm(v3, ord=2)}')

Скалярное произведение в1, в2, в3:
[ 0.    0.   -0.25]
Норма вектора в1:
0.7071067811865476
Норма вектора в2:
0.7071067811865476
Норма вектора в3:
1.0


### в) векторы не ортонормированны

### г) (1,0,0),(0,1,0),(0,0,1)

In [83]:
g1 = np.array([1, 0, 0])
g2 = np.array([0, 1, 0])
g3 = np.array([0, 0, 1])

print(f'Скалярное произведение г1, г2, г3:\n{np.dot(np.dot(g1, g2), g3)}')
print(f'Норма вектора г1:\n{norm(g1, ord=2)}')
print(f'Норма вектора г2:\n{norm(g2, ord=2)}')
print(f'Норма вектора г3:\n{norm(g3, ord=2)}')

Скалярное произведение г1, г2, г3:
[0 0 0]
Норма вектора г1:
1.0
Норма вектора г2:
1.0
Норма вектора г3:
1.0


### г) векторы ортонормированны